version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  executor:
    docker:
      - image: "circleci/node:14.17.0"
jobs:
  test:
    executor: executor
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    executor: executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    executor: executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:99:ab:3e:ba:d9:a2:88:a5:5e:49:9f:ca:b0:ca:a0"
      - checkout
      - run: npm install
      - run: npm run deploy
workflows:
  test_and_build:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: main
