version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  executor:
    docker:
      - image: "circleci/node:14.17.0"
jobs:
  test:
    executor: executor
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    executor: executor
    steps:
      - checkout
      - run: npm install
      - run: npm run deploy
workflows:
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
